### PR TITLE
Handle implicitly required (non-Pulumi) providers as parameterized ones

### LINKED ISSUE #371: Parameterization values of Any TF provider not resolved when missing from "required_providers"
### What happened?

When converting a TF program that uses Any TF provider, the converter emits a specialized `package` block for that provider backed by `terraform-provider`. However, if the Any TF provider is not present in the meta block `required_providers` then the converter doesn't emit the package block, emitting PCL for a provider that does not exist (CLI tries to download but fails with 404)

### Example

example using https://registry.terraform.io/providers/hashicorp/tfe/latest
### Without required providers
```tf
resource "tfe_organization" "test-organization" {
  name  = "my-org-name"
  email = "admin@company.com"
}

resource "tfe_agent_pool" "test-agent-pool" {
  name         = "my-agent-pool-name"
  organization = tfe_organization.test-organization.name
  organization_scoped = true
}
```
Generates:
```pcl
resource "test-organization" "tfe:index:Organization" {
  name  = "my-org-name"
  email = "admin@company.com"
}

resource "test-agent-pool" "tfe:index:AgentPool" {
  name               = "my-agent-pool-name"
  organization       = test-organization.name
  organizationScoped = true
}
```
### With required providers
```tf
terraform {
    required_providers {
        tfe = {
            source  = "hashicorp/tfe"
            version = "~> 0.68.2"
        }
    }
}

resource "tfe_organization" "test-organization" {
  name  = "my-org-name"
  email = "admin@company.com"
}

resource "tfe_agent_pool" "test-agent-pool" {
  name         = "my-agent-pool-name"
  organization = tfe_organization.test-organization.name
  organization_scoped = true
}
``` 
Generates _correct_ PCL:
```
package "tfe" {
  baseProviderName    = "terraform-provider"
  baseProviderVersion = "0.8.1"
  parameterization {
    version = "0.68.2"
    name    = "tfe"
    value   = "eyJyZW1vdGUiOnsidXJsIjoiaGFzaGljb3JwL3RmZSIsInZlcnNpb24iOiIwLjY4LjIifX0="
  }
}


resource "test-organization" "tfe:index/organization:Organization" {
  name  = "my-org-name"
  email = "admin@company.com"
}

resource "test-agent-pool" "tfe:index/agentPool:AgentPool" {
  name               = "my-agent-pool-name"
  organization       = test-organization.name
  organizationScoped = true
}
```

### Output of `pulumi about`

```
CLI          
Version      3.189.0
Go Version   go1.24.6
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zaid-pulumi-corp
User           zaid-pulumi-corp
Organizations  zaid-pulumi-corp, pulumi
Token type     personal
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
### Description

When we added support for Any TF provider in the converter, we would only emit parameterized package blocks for TF providers that are specified in `required_providers` block in the Terraform program. However, if a user doesn't specify a provider in `required_providers` and we don't have it bridged then we result in issues such as the one described in #371

This PR fixes the problem by resolving implicitly required providers as parameterized ones as if they were in the `required_providers` block and resolving their version to latest (if it exists).

The implementation adds `ProviderInfoResolver` interface to the translation logic such that during tests, we handle test providers (`simple`, `complex`, `renamed` etc.) differently from what we would do to real providers since those are not specified either in a `required_providers` block.  In the main user code path, we use a default implementation of `ProviderInfoResolver` that goes out to the registry to retrieve the latest provider version.

Fixes #371

### CODE REVIEW

File: pkg/convert/tf_test.go [hunk 1]
```diff
@@ -65,3 +65,13 @@ func TestProjectListToSingleton(t *testing.T) {
...
 }
+
+func TestResolveLatestProviderVersion(t *testing.T) {
+	t.Parallel()
+	name := impliedProvider("tfe_organization")
+	provider, err := resolveRequiredProvider(name)
+	assert.NoError(t, err)
+	assert.Equal(t, "tfe", provider.Name)
+	assert.Equal(t, "registry.terraform.io/hashicorp/tfe", provider.Source)
+	assert.Equal(t, "~> 0.70.0", provider.Requirement.Required.String())
```
Comment (Zaid-Ajaj) [inline pkg/convert/tf_test.go:76]: Unfortunately this test fails if the `tfe` provider updates their version but not sure how to test this piece of code otherwise (without tons of indirection)

File: pkg/convert/testdata/programs/implicit_required_providers/pcl/diagnostics.json [hunk 2]
```diff
@@ -0,0 +1,4 @@
+[
+  "warning:implicit_required_providers/main.tf:5,1-48:Failed to get provider info:Failed to get provider info for \"tfe_organization\": could not find mapping information for provider tfe; try installing a pulumi plugin that supports this terraform provider",
```
Comment (Frassle) [inline pkg/convert/testdata/programs/implicit_required_providers/pcl/diagnostics.json:2]: Why do we get mapping warnings? If we know we're using the parameterised version can't we lookup the mapping from that?

File: pkg/convert/info.go [hunk 3]
```diff
@@ -174,3 +178,67 @@ func (s *CachingProviderInfoSource) getFromCache(provider string) (*tfbridge.Pro
...
+func resolveRequiredProvider(providerName string) (*configs.RequiredProvider, error) {
+	source := getproviders.NewRegistrySource(disco.New())
+	providerAddress, diagnostics := addrs.ParseProviderSourceString(providerName)
+	if diagnostics.HasErrors() {
+		return nil, fmt.Errorf("failed to parse provider source %q when resolving latest version: %w",
+			providerName,
+			diagnostics.Err())
+	}
+
+	versions, _, err := source.AvailableVersions(context.TODO(), providerAddress)
```
Comment (Frassle) [inline pkg/convert/info.go:204]: Worth threading a context through here correctly now.

File: pkg/convert/tf_test.go (hunk 1 above)
Comment (Frassle) [reply pkg/convert/tf_test.go:76]: Leave a comment to that effect

File: pkg/convert/testdata/programs/implicit_required_providers/pcl/diagnostics.json (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/convert/testdata/programs/implicit_required_providers/pcl/diagnostics.json]: It felt weird to add local mappings for a provider for which we load mappings on the fly. I added them now but I think the tests don't account well for parameterized providers

**Comment by Zaid-Ajaj** [comment]
Unit tests passing but blocked by #377 where one example isn't converting latest module code from https://github.com/terraform-aws-modules/terraform-aws-alb

**Review by corymhall — APPROVED** [review]
